- name: app
  type: 'nodejs:12'
  build:
      flavor: none
  relationships:
      mongodb: "mongodb:mongodb"
  dependencies:
    nodejs:
        yarn: "*"
  hooks:
      build: yarn install
  web:
      commands:
          start: yarn start
  variables:
      env:
          MONGO_URI: mongodb://main:$main@main:27017/main
          # Website administration password:
          MONITORER_ADMIN_PASSWORD: changeme
          # Website administration username:
          MONITORER_ADMIN_USER: admin
          # Website title for Monitorer dashboard:
          MONITORER_TITLE: production